######################################################################
# Automatically generated by qmake (3.1) Sun Jun 1 03:07:08 2025
# (But manually corrected for a simple app structure)
######################################################################

QT += core gui widgets

CONFIG += c++17
TARGET = PrintagoQtApp
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API for details in order to know how to port your code away
# from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    main.cpp \
    mainwindow.cpp \
    loginpage.cpp \
    dashboardpage.cpp \
    camerafeedpage.cpp \
    jobmanagementpage.cpp \
    settingspage.cpp \
    services/MockAuthService.cpp \
    services/MockDataService.cpp \
    services/MockCameraService.cpp

HEADERS += \
    mainwindow.h \
    loginpage.h \
    dashboardpage.h \
    camerafeedpage.h \
    jobmanagementpage.h \
    settingspage.h \
    services/MockAuthService.h \
    include/Printago/Agents/IAuthService.h \
    services/MockDataService.h \
    include/Printago/Agents/IDataService.h \
    services/MockCameraService.h \
    include/Printago/Agents/ICameraService.h


# Add include path for Printago/Agents
INCLUDEPATH += $$PWD/include

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
